### ISSUE TITLE
webservice must allow file downloads

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/moodle-docker#1]
error: 

{
error: "Access control exception",
errorcode: "accessexception",
stacktrace: "* line 58 of /webservice/pluginfile.php: webservice_access_exception thrown
",
debuginfo: "Web service file downloading must be enabled in external service settings
Error code: accessexception",
reproductionlink: "http://host.docker.internal:8085/"
}

fix: 

![fix](https://github.com/Glutamat42/moodle-docker/assets/11510925/df6d82b8-49fb-4cd5-b53c-e43d28a6b2e4)
Setting ist in der external services im server tab

**Comment by SoraMakes** [comment]
not an issue of this project, fixed in plugin (https://github.com/ProjektAdLer/MoodlePluginLocal/commit/2b39dc8f353ec43a550fe90e50a2ab19c10943ce)
